services:
 pgdatabase:
  image: postgres:13
  environment:
   - POSTGRES_USER=root
   - POSTGRES_PASSWORD=root
   - POSTGRES_DB=green_taxi
  volumes:
   - ./green_taxi_progres_data:/var/lib/postgressql/data:rw
  ports:
   - "5432:5432"
 pgadmin:
  image: dpage/pgadmin4
  environment:
   - PGADMIN_DEFAULT_EMAIL=admin@admin.com
   - PGADMIN_DEFAULT_PASSWORD=root
  ports:
   - "8080:80"